# Generated by Django 3.1.1 on 2020-11-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assignees',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
